//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AscGenDotNet.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AscGenDotNet.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string _About {
            get {
                return ResourceManager.GetString("&About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add File.
        /// </summary>
        internal static string _Add_File {
            get {
                return ResourceManager.GetString("&Add File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("&Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("&Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Convert.
        /// </summary>
        internal static string _Convert {
            get {
                return ResourceManager.GetString("&Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Default.
        /// </summary>
        internal static string _Default {
            get {
                return ResourceManager.GetString("&Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string _File {
            get {
                return ResourceManager.GetString("&File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full Screen.
        /// </summary>
        internal static string _Full_Screen {
            get {
                return ResourceManager.GetString("&Full Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Height.
        /// </summary>
        internal static string _Height {
            get {
                return ResourceManager.GetString("&Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string _Help {
            get {
                return ResourceManager.GetString("&Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load Image.
        /// </summary>
        internal static string _Load_Image {
            get {
                return ResourceManager.GetString("&Load Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        internal static string _Ok {
            get {
                return ResourceManager.GetString("&Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string _Remove {
            get {
                return ResourceManager.GetString("&Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string _Save {
            get {
                return ResourceManager.GetString("&Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string _Settings {
            get {
                return ResourceManager.GetString("&Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string _View {
            get {
                return ResourceManager.GetString("&View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Width.
        /// </summary>
        internal static string _Width {
            get {
                return ResourceManager.GetString("&Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;Directory.
        /// </summary>
        internal static string Add__Directory {
            get {
                return ResourceManager.GetString("Add &Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Levels.
        /// </summary>
        internal static string Adjust_Levels {
            get {
                return ResourceManager.GetString("Adjust Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string All_Files {
            get {
                return ResourceManager.GetString("All Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Conversion.
        /// </summary>
        internal static string Batch_Conversion {
            get {
                return ResourceManager.GetString("Batch Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Images.
        /// </summary>
        internal static string Bitmap_Images {
            get {
                return ResourceManager.GetString("Bitmap Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Text on White.
        /// </summary>
        internal static string Black_Text_on_White {
            get {
                return ResourceManager.GetString("Black Text on White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lose.
        /// </summary>
        internal static string C_lose {
            get {
                return ResourceManager.GetString("C&lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Size.
        /// </summary>
        internal static string Character_Size {
            get {
                return ResourceManager.GetString("Character Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Magnification Level.
        /// </summary>
        internal static string Choose_the_Magnification_Level {
            get {
                return ResourceManager.GetString("Choose the Magnification Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag on an image to select an area.
        /// </summary>
        internal static string Click_and_drag_on_an_image_to_select_an_area {
            get {
                return ResourceManager.GetString("Click and drag on an image to select an area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Ramp to Clipboard.
        /// </summary>
        internal static string Copy_Ramp_to_Clipboard {
            get {
                return ResourceManager.GetString("Copy Ramp to Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        internal static string Date_Time {
            get {
                return ResourceManager.GetString("Date/Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultWidth and/or DefaultHeight must be &gt; 0.
        /// </summary>
        internal static string DefaultWidth_and_or_DefaultHeight_must_be___0 {
            get {
                return ResourceManager.GetString("DefaultWidth and/or DefaultHeight must be > 0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doubleclick to load an image, or drag and drop an image here..
        /// </summary>
        internal static string Doubleclick_to_load_an_image__or_drag_and_drop_an_image_here_ {
            get {
                return ResourceManager.GetString("Doubleclick to load an image, or drag and drop an image here.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string E_xit {
            get {
                return ResourceManager.GetString("E&xit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the characters to be used for generating the ramp.
        /// </summary>
        internal static string Enter_the_characters_to_be_used_for_generating_the_ramp {
            get {
                return ResourceManager.GetString("Enter the characters to be used for generating the ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchangeable Image Files.
        /// </summary>
        internal static string Exchangeable_Image_Files {
            get {
                return ResourceManager.GetString("Exchangeable Image Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string File_Not_Found {
            get {
                return ResourceManager.GetString("File Not Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to be converted.
        /// </summary>
        internal static string Files_to_be_converted {
            get {
                return ResourceManager.GetString("Files to be converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Selected Area.
        /// </summary>
        internal static string Fill_Selected_Area {
            get {
                return ResourceManager.GetString("Fill Selected Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Horizontally.
        /// </summary>
        internal static string Flip_Horizontally {
            get {
                return ResourceManager.GetString("Flip Horizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip Vertically.
        /// </summary>
        internal static string Flip_Vertically {
            get {
                return ResourceManager.GetString("Flip Vertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For The Best Effect This Text Should Be Readable.
        /// </summary>
        internal static string For_The_Best_Effect_This_Text_Should_Be_Readable {
            get {
                return ResourceManager.GetString("For The Best Effect This Text Should Be Readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Greyscale.
        /// </summary>
        internal static string Force_Greyscale {
            get {
                return ResourceManager.GetString("Force Greyscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Images.
        /// </summary>
        internal static string GIF_Images {
            get {
                return ResourceManager.GetString("GIF Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&amp;mport from Clipboard.
        /// </summary>
        internal static string I_mport_from_Clipboard {
            get {
                return ResourceManager.GetString("I&mport from Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        internal static string Image_Files {
            get {
                return ResourceManager.GetString("Image Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Text Sample.
        /// </summary>
        internal static string Input_Text_Sample {
            get {
                return ResourceManager.GetString("Input Text Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ASCII Ramp.
        /// </summary>
        internal static string Invalid_ASCII_Ramp {
            get {
                return ResourceManager.GetString("Invalid ASCII Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Output Directory.
        /// </summary>
        internal static string Invalid_Output_Directory {
            get {
                return ResourceManager.GetString("Invalid Output Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Output Size.
        /// </summary>
        internal static string Invalid_Output_Size {
            get {
                return ResourceManager.GetString("Invalid Output Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings file. Please delete it or save a new one.
        /// </summary>
        internal static string Invalid_settings_file__Please_delete_it_or_save_a_new_one {
            get {
                return ResourceManager.GetString("Invalid settings file. Please delete it or save a new one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Selection.
        /// </summary>
        internal static string Invert_Selection {
            get {
                return ResourceManager.GetString("Invert Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Images.
        /// </summary>
        internal static string JPEG_Images {
            get {
                return ResourceManager.GetString("JPEG Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels Adjustment.
        /// </summary>
        internal static string Levels_Adjustment {
            get {
                return ResourceManager.GetString("Levels Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Selected Area.
        /// </summary>
        internal static string Lock_Selected_Area {
            get {
                return ResourceManager.GetString("Lock Selected Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnification.
        /// </summary>
        internal static string Magnification {
            get {
                return ResourceManager.GetString("Magnification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Med.
        /// </summary>
        internal static string Med {
            get {
                return ResourceManager.GetString("Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        internal static string Median {
            get {
                return ResourceManager.GetString("Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Memory, Could not convert the image.
        /// </summary>
        internal static string Out_of_Memory__Could_not_convert_the_image {
            get {
                return ResourceManager.GetString("Out of Memory, Could not convert the image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output as.
        /// </summary>
        internal static string Output_as {
            get {
                return ResourceManager.GetString("Output as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        internal static string Output_Directory {
            get {
                return ResourceManager.GetString("Output Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Filenames.
        /// </summary>
        internal static string Output_Filenames {
            get {
                return ResourceManager.GetString("Output Filenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Image Sample.
        /// </summary>
        internal static string Output_Image_Sample {
            get {
                return ResourceManager.GetString("Output Image Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Size.
        /// </summary>
        internal static string Output_Size {
            get {
                return ResourceManager.GetString("Output Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        internal static string pixels {
            get {
                return ResourceManager.GetString("pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an output directory.
        /// </summary>
        internal static string Please_enter_an_output_directory {
            get {
                return ResourceManager.GetString("Please enter an output directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Network Graphics Images.
        /// </summary>
        internal static string Portable_Network_Graphics_Images {
            get {
                return ResourceManager.GetString("Portable Network Graphics Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        internal static string Ramp {
            get {
                return ResourceManager.GetString("Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        internal static string Remove_All {
            get {
                return ResourceManager.GetString("Remove All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File After Conversion.
        /// </summary>
        internal static string Remove_File_After_Conversion {
            get {
                return ResourceManager.GetString("Remove File After Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selection.
        /// </summary>
        internal static string Remove_Selection {
            get {
                return ResourceManager.GetString("Remove Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string Save_As {
            get {
                return ResourceManager.GetString("Save As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as an &amp;Image.
        /// </summary>
        internal static string Save_as_an__Image {
            get {
                return ResourceManager.GetString("Save as an &Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log As.
        /// </summary>
        internal static string Save_Log_As {
            get {
                return ResourceManager.GetString("Save Log As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings as Default.
        /// </summary>
        internal static string Save_Settings_as_Default {
            get {
                return ResourceManager.GetString("Save Settings as Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the output before closing.
        /// </summary>
        internal static string Save_the_output_before_closing {
            get {
                return ResourceManager.GetString("Save the output before closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to a Text File.
        /// </summary>
        internal static string Save_to_a_Text_File {
            get {
                return ResourceManager.GetString("Save to a Text File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory from which to import image files.
        /// </summary>
        internal static string Select_a_directory_from_which_to_import_image_files {
            get {
                return ResourceManager.GetString("Select a directory from which to import image files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select None.
        /// </summary>
        internal static string Select_None {
            get {
                return ResourceManager.GetString("Select None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory in which to save the converted images.
        /// </summary>
        internal static string Select_the_directory_in_which_to_save_the_converted_images {
            get {
                return ResourceManager.GetString("Select the directory in which to save the converted images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Area Border Colour.
        /// </summary>
        internal static string Selection_Area_Border_Colour {
            get {
                return ResourceManager.GetString("Selection Area Border Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Area Fill Colour.
        /// </summary>
        internal static string Selection_Area_Fill_Colour {
            get {
                return ResourceManager.GetString("Selection Area Fill Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpen.
        /// </summary>
        internal static string Sharpen {
            get {
                return ResourceManager.GetString("Sharpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpening Mask.
        /// </summary>
        internal static string Sharpening_Mask {
            get {
                return ResourceManager.GetString("Sharpening Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpening Method.
        /// </summary>
        internal static string Sharpening_Method {
            get {
                return ResourceManager.GetString("Sharpening Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Extension.
        /// </summary>
        internal static string Show_Extension {
            get {
                return ResourceManager.GetString("Show Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Full Path.
        /// </summary>
        internal static string Show_Full_Path {
            get {
                return ResourceManager.GetString("Show Full Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some characters may not make it in to the ramp.
        /// </summary>
        internal static string Some_characters_may_not_make_it_in_to_the_ramp {
            get {
                return ResourceManager.GetString("Some characters may not make it in to the ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Character Size.
        /// </summary>
        internal static string Specify_Character_Size {
            get {
                return ResourceManager.GetString("Specify Character Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Settings.
        /// </summary>
        internal static string Text_Settings {
            get {
                return ResourceManager.GetString("Text Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIF Images.
        /// </summary>
        internal static string TIF_Images {
            get {
                return ResourceManager.GetString("TIF Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select this font.
        /// </summary>
        internal static string Unable_to_select_this_font {
            get {
                return ResourceManager.GetString("Unable to select this font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown or Unsupported File.
        /// </summary>
        internal static string Unknown_or_Unsupported_File {
            get {
                return ResourceManager.GetString("Unknown or Unsupported File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsharp Mask.
        /// </summary>
        internal static string Unsharp_Mask {
            get {
                return ResourceManager.GetString("Unsharp Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Characters.
        /// </summary>
        internal static string Valid_Characters {
            get {
                return ResourceManager.GetString("Valid Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Metafile Images.
        /// </summary>
        internal static string Windows_Metafile_Images {
            get {
                return ResourceManager.GetString("Windows Metafile Images", resourceCulture);
            }
        }
    }
}
